/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
static yyconst short int yy_acclist[200] =
    {   0,
       45,   45,   51,   49,   50,   45,   49,   50,   44,   50,
       34,   49,   50,   49,   50,   49,   50,   49,   50,   49,
       50,   49,   50,   37,   49,   50,   38,   49,   50,   26,
       49,   50,   24,   49,   50,   36,   49,   50,   25,   49,
       50,   27,   49,   50,   18,   49,   50,   35,   49,   50,
       30,   49,   50,   29,   49,   50,   30,   49,   50,   14,
       49,   50,   14,   49,   50,   41,   49,   50,   42,   49,
       50,   49,   50,   14,   49,   50,   14,   49,   50,   14,
       49,   50,   14,   49,   50,   14,   49,   50,   14,   49,
       50,   14,   49,   50,   14,   49,   50,   14,   49,   50,

       14,   49,   50,   39,   49,   50,   49,   50,   40,   49,
       50,   45,   31,   15,   48,   32,   20,   17,   22,   23,
       18,   43,   18,   46,   46,   30,   28,   14,   14,   14,
       16,   14,   14,   14,   14,   14,    7,   14,   14,   14,
       14,   14,   14,   14,   14,   33,   43,   19,   14,   14,
       14,   14,   14,    9,   14,    1,   14,   14,   14,   14,
       14,   14,   14,   14,    3,   14,   14,    8,   14,   14,
       14,   14,   14,   14,    5,   14,   14,   14,   14,    2,
       14,   14,   14,   13,   14,   14,   10,   14,   47,   14,
        4,   14,   12,   14,   11,   14,    6,   14,   21

    } ;

static yyconst short int yy_accept[142] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   14,   16,   18,
       20,   22,   24,   27,   30,   33,   36,   39,   42,   45,
       48,   51,   54,   57,   60,   63,   66,   69,   72,   74,
       77,   80,   83,   86,   89,   92,   95,   98,  101,  104,
      107,  109,  112,  113,  114,  114,  115,  115,  116,  116,
      116,  117,  117,  118,  118,  119,  120,  121,  122,  123,
      123,  125,  126,  127,  128,  129,  130,  131,  131,  132,
      133,  134,  135,  136,  137,  139,  140,  141,  142,  143,
      144,  145,  146,  147,  147,  147,  148,  149,  150,  151,
      152,  153,  154,  156,  158,  159,  160,  161,  162,  163,

      164,  164,  164,  165,  167,  168,  170,  171,  172,  173,
      174,  175,  177,  178,  178,  178,  179,  180,  182,  183,
      184,  186,  187,  189,  190,  190,  190,  191,  193,  195,
      197,  199,  199,  199,  199,  199,  199,  199,  199,  200,
      200
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    1,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,   24,   25,   26,   27,   27,   27,   28,   27,
       27,   27,   27,   27,   27,   29,   27,   27,   27,   27,
       27,   30,   27,   31,   27,   27,   27,   27,   27,   27,
       32,    1,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   27,   27,   45,   27,   46,
       47,   48,   27,   49,   50,   51,   52,   53,   54,   27,
       27,   27,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    5,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static yyconst short int yy_base[150] =
    {   0,
        0,    0,  306,  307,   56,  307,  283,  298,   54,   60,
       66,  293,  307,  307,  289,  287,  307,   61,  282,   47,
      307,  277,  276,  275,  277,   53,  307,  307,  261,   51,
       40,   52,   67,   74,   73,   77,   80,   81,   82,  307,
      238,  307,  100,  307,  287,  286,  125,  269,  262,  243,
      131,  278,  277,  273,  272,  307,  307,  265,    0,  264,
       86,  262,  307,  307,    0,  253,   88,  233,  224,   87,
       89,   92,   90,   94,  234,   97,   91,  107,  108,  102,
      117,  126,  307,  217,  207,    0,  225,  127,  110,  143,
      133,  145,  224,  223,  144,  146,  147,  148,  149,  150,

      211,  195,  152,  220,  155,  219,  153,  156,  157,  158,
      163,  217,  165,  209,  182,  194,  168,  212,  170,  164,
      211,  172,  209,  198,  187,  208,  166,  206,  205,  203,
      202,  157,  175,  208,    0,  169,  203,  107,   48,  307,
      246,  251,  256,  259,  260,  265,  270,  272,  277
    } ;

static yyconst short int yy_def[150] =
    {   0,
      140,    1,  140,  140,  140,  140,  140,  141,  140,  140,
      140,  142,  140,  140,  143,  140,  140,  140,  140,  144,
      140,  140,  140,  140,  145,  145,  140,  140,  146,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  140,
      140,  140,  140,  140,  141,  141,  140,  140,  140,  140,
      140,  142,  142,  143,  143,  140,  140,  140,  147,  140,
      144,  144,  140,  140,  148,  145,  145,  146,  146,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  140,  140,  140,  147,  140,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      140,  140,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  140,  140,  145,  145,  145,  145,  145,
      145,  145,  145,  140,  140,  140,  145,  145,  145,  145,
      145,  140,  140,  140,  149,  149,  149,  149,  149,    0,
      140,  140,  140,  140,  140,  140,  140,  140,  140
    } ;

static yyconst short int yy_nxt[365] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,    4,   19,   20,   21,
       22,   23,   24,   10,   10,   25,   25,   25,   26,   25,
       25,   27,   28,   29,   25,   25,   25,   30,   31,   32,
       33,   25,   25,   34,   25,   25,   25,   35,   36,   37,
       25,   25,   38,   39,   40,   41,   42,   43,   65,   43,
       47,   47,   47,   60,  137,   61,   47,   47,   47,   65,
       65,   65,   47,   47,   51,   48,   57,   47,   47,   58,
       67,   48,   49,   47,   47,   65,   71,   48,   49,   47,
       47,   65,   65,   70,   49,   65,   72,   50,   65,   65,

       65,   43,   60,   43,   61,   65,   65,   65,   65,   65,
       65,   73,   65,   74,   75,   65,   78,   79,   88,   76,
       65,   77,   89,  137,   82,   65,   65,   81,   65,  139,
       80,   47,   47,   47,   95,   65,   92,   47,   47,   47,
       90,   91,   93,   97,   65,   65,   48,   94,   47,   47,
       98,   65,   48,   49,   47,   47,  103,   96,  104,   49,
       99,   65,   65,   65,   65,   65,   65,   65,   65,  100,
       65,   65,  106,   65,   65,   65,   65,  116,  134,  105,
      107,   65,   65,   65,   65,  137,   65,  112,   65,  108,
       65,  111,  110,   67,  113,  135,  133,  109,  121,  117,

      126,  126,  126,  118,  123,  120,  119,  128,  122,  130,
      129,  134,   65,  131,  126,  126,  126,  126,  126,  137,
       65,   65,  127,   65,   65,  132,   49,   65,  135,   65,
       65,  126,  126,  125,  124,   65,   49,   65,   65,  115,
      114,   65,   65,   87,  102,  138,   45,  101,   45,   45,
       45,   52,   65,   52,   52,   52,   54,   69,   54,   54,
       54,   62,   62,   66,   66,   68,   69,   68,   68,   68,
       86,   65,   86,   86,   86,   65,   65,  136,  140,  136,
      136,  136,   87,   58,   55,   55,   53,   53,   85,   84,
       48,   46,   46,   83,   69,   65,   63,   64,   63,   59,

       56,   55,   53,   46,   44,  140,    3,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140
    } ;

static yyconst short int yy_chk[365] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,   31,    5,
        9,    9,    9,   20,  139,   20,   10,   10,   10,   30,
       32,   26,   11,   11,   11,    9,   18,    9,    9,   18,
       26,   10,    9,   10,   10,   33,   31,   11,   10,   11,
       11,   35,   34,   30,   11,   36,   32,    9,   37,   38,

       39,   43,   61,   43,   61,   70,   67,   71,   73,   77,
       72,   33,   74,   33,   34,   76,   36,   37,   67,   34,
       80,   35,   70,  138,   39,   78,   79,   38,   89,  138,
       37,   47,   47,   47,   77,   81,   73,   51,   51,   51,
       71,   72,   74,   79,   82,   88,   47,   76,   47,   47,
       80,   91,   51,   47,   51,   51,   88,   78,   89,   51,
       81,   90,   95,   92,   96,   97,   98,   99,  100,   82,
      103,  107,   91,  105,  108,  109,  110,  103,  133,   90,
       92,  111,  120,  113,  127,  136,  117,   99,  119,   95,
      122,   98,   97,  127,  100,  133,  132,   96,  110,  105,

      116,  116,  116,  107,  113,  109,  108,  117,  111,  120,
      119,  134,  116,  122,  126,  126,  126,  116,  116,  137,
      131,  130,  116,  129,  128,  125,  124,  123,  134,  121,
      118,  126,  126,  115,  114,  112,  126,  106,  104,  102,
      101,   94,   93,   87,   85,  137,  141,   84,  141,  141,
      141,  142,   75,  142,  142,  142,  143,   69,  143,  143,
      143,  144,  144,  145,  145,  146,   68,  146,  146,  146,
      147,   66,  147,  147,  147,  148,  148,  149,   62,  149,
      149,  149,   60,   58,   55,   54,   53,   52,   50,   49,
       48,   46,   45,   41,   29,   25,   24,   23,   22,   19,

       16,   15,   12,    8,    7,    3,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include "hashtable.h"
    #include "parser.tab.h"

    Hash** tabela_reservada;
    Hash** tabela_simbolos;
    int line = 1;
#line 534 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 50 "lex.l"



#line 689 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 141 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 307 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 53 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "TIPO_INT");    
                return INT;
            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "TIPO_FLOAT");             
                return FLOAT;
            }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "TIPO_CHAR");
                return CHAR;
            }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "TIPO_DOUBLE");
                return DOUBLE;
            }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "TIPO_VOID");
                return VOID;
            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "TIPO_STRING");
                return STRING;
            }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "IF");                
                return IF;
            }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "ELSE");              
                return ELSE;
            }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "FOR");                                 
                return FOR;
            }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "WHILE");                                  
                return WHILE;
            }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "RETURN");                   
                return RETURN;
            }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 108 "lex.l"
{    strcpy(yylval.no_obj.strNome, (yytext));
                 inserir(tabela_reservada, yytext, "PRINTF");                                
                return PRINTF;
            }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 113 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
               inserir(tabela_reservada, yytext, "SCANF");                               
               return SCANF;
            }         
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 118 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_simbolos, yytext, "ID");                                
                return ID;
            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 123 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_simbolos, yytext, "STRING");                                
                return STR;
            }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 128 "lex.l"
{    strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_simbolos, yytext, "ESCRITA");                                
                return ESCRITA;           
            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 133 "lex.l"
{    strcpy(yylval.no_obj.strNome, (yytext));
               inserir(tabela_simbolos, yytext, "LEITURA");                                 
               return LEITURA;           
            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 138 "lex.l"
{  strcpy(yylval.no_obj.strNome, (yytext));
               inserir(tabela_simbolos, yytext, "DIG_INT");                                 
                return  INTEGER;
            }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 143 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_simbolos, yytext, "DIG_REAL");                  
                return REAL;
            }           
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "lex.l"
{   strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_simbolos, yytext, "CARACTER");                                
                return CARACTER;
            }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 153 "lex.l"
{  strcpy(yylval.no_obj.strNome, (yytext));
                inserir(tabela_reservada, yytext, "NOME_BIBLIOTECA");                                 
                return BIBLIOTECA;
            } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 158 "lex.l"
{  inserir(tabela_reservada, yytext, "INCREMENTO");                       
                return INCREMENTO;
             }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 162 "lex.l"
{  inserir(tabela_reservada, yytext, "DECREMENTO");                        
                return DECREMENTO;
             }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 166 "lex.l"
{  inserir(tabela_reservada, yytext, "ADICAO");                   
               return ADICAO;
            }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 170 "lex.l"
{   inserir(tabela_reservada, yytext, "SUBTRACAO");                    
                return SUBTRACAO;
            }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 174 "lex.l"
{   inserir(tabela_reservada, yytext, "MULTIPLICACAO");                       
                    return MULTIPLICACAO;
                }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 178 "lex.l"
{   inserir(tabela_reservada, yytext, "DIVISAO");                   
                return DIVISAO;
            }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 182 "lex.l"
{   inserir(tabela_reservada, yytext, "IGUAL");                    
                return IGUAL;
            }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 186 "lex.l"
{   inserir(tabela_reservada, yytext, "ATRIBUICAO");                        
                    return ATRIBUICAO;
                }            
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 190 "lex.l"
{   inserir(tabela_reservada, yytext, "COMPARACAO");                       
                    return COMPARACAO;
                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 194 "lex.l"
{   inserir(tabela_reservada, yytext, "DIFERENTE");
                    return DIFERENTE;
                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 198 "lex.l"
{   inserir(tabela_reservada, yytext, "AND");
                    return AND;
                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 202 "lex.l"
{   inserir(tabela_reservada, yytext, "OR");
                    return OR;
                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 206 "lex.l"
{   inserir(tabela_reservada, yytext, "NOT");
                    return NOT;
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 210 "lex.l"
{   inserir(tabela_reservada, yytext, "PONTO_VIRGULA");
                    return PONTO_VIRGULA;
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 214 "lex.l"
{   inserir(tabela_reservada, yytext, "VIRGULA");
                    return VIRGULA;
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 218 "lex.l"
{   inserir(tabela_reservada, yytext, "A_PARENT");
                    return  A_PARENT;
                }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 222 "lex.l"
{   inserir(tabela_reservada, yytext, "F_PARENT");
                    return F_PARENT;
                }           
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 226 "lex.l"
{   inserir(tabela_reservada, yytext, "A_CHAVE");
                    return A_CHAVE;
                }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 230 "lex.l"
{   inserir(tabela_reservada, yytext, "F_CHAVE"); 
                    return F_CHAVE;
                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 234 "lex.l"
{   inserir(tabela_reservada, yytext, "A_COLCHET");
                    return A_COLCHET;
                }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 238 "lex.l"
{   inserir(tabela_reservada, yytext, "F_COLCHET");
                    return F_COLCHET;
                }       
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 242 "lex.l"
{   inserir(tabela_simbolos, yytext, "COMENTARIO");
                   strcpy(yylval.no_obj.strNome, (yytext));
                    return COMENTARIO;
                }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 247 "lex.l"
{line++;}            
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 249 "lex.l"
{;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 251 "lex.l"
{
                    printf("\nErro Lexico na linha %d , token  %s nao identificado\n", yylineno, yytext);
                    
                }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 256 "lex.l"
{
                    printf("\nErro Lexico na linha %d , token  %s nao identificado\n", yylineno, yytext);
                    
                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 261 "lex.l"
{
                  printf("\nErro Lexico na linha %d , token  %s nao identificado\n", yylineno, yytext);
                  
                }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 266 "lex.l"
{
                    printf("\nErro Lexico na linha %d , token  %s nao identificado\n", yylineno, yytext); 
                
                }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 270 "lex.l"
ECHO;
	YY_BREAK
#line 1150 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 141 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 141 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 140);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 270 "lex.l"


int yywrap(){
    return 1;
}
